//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_Container : DbContext
    {
        public Model_Container()
            : base("name=Model_Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>()
           .HasMany(a => a.Genres)
           .WithMany(b => b.Movies)
           .Map(m =>
           {
               m.ToTable("MovieGenre"); 
               m.MapLeftKey("Movies_IDMovies");
               m.MapRightKey("Genres_IDGenre");
           });
            modelBuilder.Entity<Movie>()
           .HasMany(a => a.Actors)
           .WithMany(b => b.Movies)
           .Map(m =>
           {
               m.ToTable("MovieActor"); 
               m.MapLeftKey("Movies_IDMovies");
               m.MapRightKey("Actors_IDActor");
           });
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<UploadedPoster> UploadedPosters { get; set; }
    }
}
